In [1]:
import numpy as np


In [2]:
l = [1,2,3,4,5,6]
ar = np.array(l)
ar

array([1, 2, 3, 4, 5, 6])

In [3]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [4]:
np.matrix(l)

matrix([[1, 2, 3, 4, 5, 6]])

In [5]:
d = np.copy(ar)

In [6]:
d[0] = 100
d[0],ar[0]

(100, 1)

In [7]:
np.fromfunction(lambda i,j : i-j,(3,3),dtype = float)

array([[ 0., -1., -2.],
       [ 1.,  0., -1.],
       [ 2.,  1.,  0.]])

In [10]:
np.fromiter([i*i for i in range(0,9)],dtype=float)

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64.])

In [11]:
string = '12 23 4 5 6 7'
np.fromstring(string,sep = " ")

array([12., 23.,  4.,  5.,  6.,  7.])

In [12]:
ar.ndim

1

In [13]:
ar.size

6

In [14]:
ar.shape

(6,)

In [15]:
list(range(5))

[0, 1, 2, 3, 4]

In [16]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [17]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [21]:
m = np.ones(5)

In [22]:
print(m)
print(m*3)

[1. 1. 1. 1. 1.]
[3. 3. 3. 3. 3.]


In [23]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.logspace(2,4,10,base = 2,dtype = int)

array([ 4,  4,  5,  6,  7,  8, 10, 11, 13, 16])

In [27]:
arr = np.random.randn(3,4)
arr

array([[ 8.25193802e-02,  3.51990021e-01, -3.20790571e-03,
        -4.65575337e-01],
       [-4.05823235e-01,  1.25861156e+00, -1.67872314e+00,
        -1.21913883e-03],
       [-5.32321812e-01,  3.80405454e-01,  1.67557421e+00,
        -6.93957012e-01]])

In [32]:
import pandas as pd
df = pd.DataFrame(arr,columns=['A','B','C','D'])

In [33]:
df

A         B         C         D
0  0.082519  0.351990 -0.003208 -0.465575
1 -0.405823  1.258612 -1.678723 -0.001219
2 -0.532322  0.380405  1.675574 -0.693957

In [35]:
df.std()

A    0.324682
B    0.515431
C    1.677149
D    0.353004
dtype: float64

In [36]:
np.random.randint(1,110,(3,4))

array([[65, 12, 32, 91],
       [81, 47, 10, 85],
       [ 4, 54, 27, 80]])

In [37]:
arr.reshape(6,2)

array([[ 8.25193802e-02,  3.51990021e-01],
       [-3.20790571e-03, -4.65575337e-01],
       [-4.05823235e-01,  1.25861156e+00],
       [-1.67872314e+00, -1.21913883e-03],
       [-5.32321812e-01,  3.80405454e-01],
       [ 1.67557421e+00, -6.93957012e-01]])

In [42]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(2,3,(3,3))
print(arr1)
print(arr2)

[[2 1 1]
 [2 1 2]
 [1 1 1]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [43]:
arr1*arr2

array([[4, 2, 2],
       [4, 2, 4],
       [2, 2, 2]])

In [44]:
arr1@arr2

array([[ 8,  8,  8],
       [10, 10, 10],
       [ 6,  6,  6]])

In [45]:
np.log10(ar)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125])

In [46]:
np.sqrt(ar)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [48]:
print(np.repeat(ar,3))
print(np.roll(ar,2))
print(np.diag(ar))

[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6]
[5 6 1 2 3 4]
[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [49]:
~ar

array([-2, -3, -4, -5, -6, -7])

In [50]:
arr = np.array(['ch','lis'])
arr

array(['ch', 'lis'], dtype='<U3')

In [51]:
np.char.capitalize(arr)

array(['Ch', 'Lis'], dtype='<U3')

In [52]:
np.min(ar)

1

In [53]:
np.sort(arr)

array(['ch', 'lis'], dtype='<U3')

In [55]:
np.count_nonzero(ar)

6

In [56]:
np.where(ar>3)

(array([3, 4, 5], dtype=int64),)

In [60]:
ar.byteswap()

array([ 16777216,  33554432,  50331648,  67108864,  83886080, 100663296])

In [61]:
import numpy.matlib as nm
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])